apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: topolvm-provisioner
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

