apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app
  name: apache-pod-service
spec:
  ports:
  - nodePort: 30303
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apache-pod
  type: NodePort
