apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app
  name: apache-pod-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: apache-pod
  type: ClusterIP
